# Generated by Django 5.2.2 on 2025-06-10 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionselector',
            name='question',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectorrecipient',
            name='get_recipient',
            field=models.CharField(default='GetRecip', max_length=150),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonials',
            name='video_add',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
