# Generated by Django 5.2.2 on 2025-06-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
