# Generated by Django 5.2.2 on 2025-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_order', '0002_questionselector_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='video_add',
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='comments',
            field=models.CharField(default='Comments', max_length=250),
        ),
    ]
