# Generated by Django 5.2.2 on 2025-06-12 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_order', '0003_remove_testimonials_video_add_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100)),
                ('cover_choice', models.CharField(blank=True, max_length=100)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_photos/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_order.bookorder')),
            ],
        ),
        migrations.CreateModel(
            name='BookQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Photo_add',
        ),
        migrations.DeleteModel(
            name='Preview',
        ),
        migrations.DeleteModel(
            name='QuestionSelector',
        ),
        migrations.DeleteModel(
            name='SelectorRecipient',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.AddField(
            model_name='bookanswer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_order.bookorder'),
        ),
        migrations.AddField(
            model_name='bookanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_order.bookquestion'),
        ),
    ]
