# Generated by Django 5.2.2 on 2025-06-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_order', '0004_bookanswer_bookorder_bookphoto_bookquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SelectorRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_recipient', models.CharField(default='GetRecip', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='Comments', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookphoto',
            name='order',
        ),
        migrations.DeleteModel(
            name='BookAnswer',
        ),
        migrations.DeleteModel(
            name='BookQuestion',
        ),
        migrations.DeleteModel(
            name='BookOrder',
        ),
        migrations.DeleteModel(
            name='BookPhoto',
        ),
    ]
